Refactor konstantin
daisybio/DIGGER pull request #52
Opened 2024-09-10 12:39 UTC by PelzKo

2024-09-10 13:30 UTC, PelzKo commented
This should be fine now. I implemented the whole thing with the sharable link and how long files will be saved.
One question I still had is how to set up the migrations. I created the migration files with makeMigrations now, but I am not sure that is correct

2024-09-11 12:54 UTC, Eeeeelias requested changes
I like this implementation, but there are still a few things we need to take care of before merging. Feel free to share your thoughts in case I missed something.

2024-09-11 12:54 UTC, Eeeeelias commented on container/DomainExplorer/settings/production.py
For the PR, let's change it back to False, since we'll use this in production

2024-09-11 12:54 UTC, Eeeeelias commented on container/domain/static/domain/loadStore.js
This currently makes it such that in the Previous Analyses list on the setup page, it shows a wrong date.
As it is, the `createHtmlTemplate` function has a expiresInDays parameter, which is always set to 7. We need to update this, to properly reflect when this analysis was created. The function is called in the nease_setup.html

2024-09-11 12:54 UTC, Eeeeelias commented on container/domain/templates/visualization/nease_result.html
Multiple things here:
1. Good addition with the custom name!
2. We use Boostrap (v4.6) for our styling, so let's stick with that: For the dropdown we can use this: https://getbootstrap.com/docs/4.6/components/dropdowns/ and for the link a normal button (e.g. secondary, info or just link): https://getbootstrap.com/docs/4.6/components/buttons/.
3. I like that it shows you how long  the analysis is stored still. Let's maybe not call it Storage duration though, I think something like "Analysis availablity" would be more user friendly. 
4. Just as a visual thing, could you maybe try moving these new option to the right side of the jumbotron instead of at the bottom. We have lots of empty space there that will realistically not be used otherwise. Here's a quick sketch of what I mean:
![example](https://github.com/user-attachments/assets/cf9ecba0-b790-4176-9ab4-666a1323fa92)
5. The "Click to copy" button does not work. Currently, when I try to copy the link, it says: 
```TypeError: navigator.clipboard is undefined```. I'm using firefox on ubuntu.

Otherwise this is fine.

2024-09-11 12:54 UTC, Eeeeelias commented on docker/web/auto_clean.sh
Is there a reason `FOLDER_FOUR` is not in the FOLDERS list? Same with `DELETION_TIMES`, I don't see an obvious way where these would also be deleted at some point? I am also not super familiar with bash so maybe I'm missing something here.

Additionally, I think we don't need to delete the media files every day, removing them every month is fine. Maybe even 6 months. in current DIGGER they're not being deleted at all, but also, having saved generated images is not bad, if multiple users ask for the same splicing isoforms / the same user comes back a few days later.

2024-09-11 12:54 UTC, Eeeeelias commented on container/DomainExplorer/settings/production.py
Alternatively, an env variable setting this variable would also be fine.

2024-09-11 12:59 UTC, PelzKo commented on container/DomainExplorer/settings/production.py
You are right, I could have sworn that I changed it back...

2024-09-11 13:01 UTC, PelzKo commented on docker/web/auto_clean.sh
Nope, I just added it later and I missed it. Thank you for spotting that!

2024-09-11 13:02 UTC, PelzKo commented on docker/web/auto_clean.sh
And regarding the media. I changed it now to be deleted every six months so nothing that an analysis still needs is deleted

2024-09-12 12:13 UTC, PelzKo commented on container/domain/templates/visualization/nease_result.html
Changed the dropdown and button, renamed the "Storage duration".
I will leave the summary stuff like this for now and create an issue so we can tackle it in the future, as it is only relevant on very big screens.
Click to copy should work, the navigator.clipboard API is just not available in http contexts. I added a fallback though with a deprecated, but working version, so that should work in any case now

2024-09-12 12:14 UTC, PelzKo commented on container/domain/static/domain/loadStore.js
Changed it by saving the date of creation in local storage as well

2024-09-12 12:45 UTC, PelzKo commented
That should be it
Can you check one last time whether I missed anything?

2024-09-12 14:39 UTC, Eeeeelias requested changes
After these small changes I think we can merge this and be good!

2024-09-12 14:39 UTC, Eeeeelias commented on container/domain/static/domain/initStore.js
This now updates every time the user calls for their analysis. Is this intentional? 
We can leave it and say this is the time of last access. As long as the user is aware of how long his analysis is still available for.

2024-09-12 14:39 UTC, Eeeeelias commented on container/domain/templates/visualization/nease_result.html
Still some changes I would like to make here:
1. Let's rename "Delete tonight" into "Do not save". I don't think it's the users business to know when we actually delete the file on the server, we just delete it that same day.
2. The copy to clipboard option still doesn't work for me. I pasted the error to ChatGPT and got the following suggestion: 
```js
//have a fallback in case the clipboard API is not supported
                if (!navigator.clipboard) {
                    // Create a temporary textarea element to copy the text from
                    const tempTextArea = document.createElement("textarea");
                    tempTextArea.value = copyText;
                    tempTextArea.style.position = "absolute";
                    tempTextArea.style.left = "-9999px";
                    document.body.appendChild(tempTextArea);

                    tempTextArea.select();
                    ...
                    body.removeChild(tempTextArea);

```
Next, we have to put this `navigator.clipboard.writeText(...)` in an else clause, otherwise it'll copy but still throw an error.

3. Instead of the current alert we get, we should resort to a more UX-friendly tooltip. We can just have something like this for the button:
```html
              <button type="button" class="btn btn-secondary" id="copyButton" data-toggle="tooltip"
              data-placement="top" title="Copy me!" onclick="copyDivToClipboard()">Click to copy</button>
```
and then change the attributes once the link has been successfully copied:
```js
var copyButton = $('#copyButton')
copyButton.attr('title', 'Copied!')
          .tooltip('dispose')
          .tooltip('show');
 // Hide the tooltip after 2 seconds
setTimeout(function() {
  copyButton.tooltip('hide')
            .attr('title', 'Click to copy')
            .tooltip('dispose')
            .tooltip();
}, 2000); 
```
In that, we could also give an info if something didn't work. e.g. a tooltip saying there was an error.

I think if these changes are implemented we are good to go

2024-09-12 15:01 UTC, PelzKo commented on container/domain/static/domain/initStore.js
Nope, I thought it was just called when the analysis was created. Let me fix it

2024-09-12 16:14 UTC, PelzKo commented on container/domain/static/domain/initStore.js
It will now check whether the id is already in local storage and only create it if it does not exist yet

2024-09-12 16:14 UTC, PelzKo commented on container/domain/templates/visualization/nease_result.html
I added in your recommendations. Thank you for them!

2024-09-12 17:29 UTC, Eeeeelias reviewed
LGTM!

I will check if the analyses behave properly over the next few days (with deletion and stuff) and open an issue if they - unexpectedly - don't.

2024-09-12 17:30 UTC, Eeeeelias approved these changes

2024-09-12 17:30 UTC, merged